### ISSUE TITLE
Resize targeting ouput window to fullscreen

### ISSUE THREAD

**Issue by HenbiPY** [Dreadbot/Dreadbots2022#14]
When you resize the actual window it screws with the positioning of the drawn target positioning. Need a way to have the target shown in the right spot on the full-screened window

**Comment by Node-Kid** [comment]
Solved with display image resize, not resizing the base image
`
width = int(imgToPush.shape[1] * 160 / 100)
        height = int(imgToPush.shape[0] * 160 / 100)
        dim = (width, height)
        resized = cv2.resize(imgToPush, dim)
        cv2.imshow('pushed image', resized)
`
