### ISSUE TITLE
Shooter - Add Ball Trajectory Math

### ISSUE THREAD

**Issue by cjohnson** [Dreadbot/Dreadbots2022#8]
# Add Ball Trajectory Math
Using the math calculated using the Desmos tool, add it to the existing Shooter class.

## Issue Prerequisites
* https://github.com/Dreadbot/Dreadbots2022/issues/2

## Feature Branch
* **shooter**

## Expectations
* Add the Desmos tool calculations to the Shooter class
* No integration needed

## Helpful Links :)
* [Desmos Tool](https://www.desmos.com/calculator/gp0kr33n4c)

## General Links
* [WPI Docs](https://docs.wpilib.org/en/stable/)
* [WPI Javadocs](https://first.wpi.edu/wpilib/allwpilib/docs/release/java/index.html)
* [WPI Examples](https://github.com/wpilibsuite/allwpilib/tree/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples)
* [CANSparkMax Javadoc](https://codedocs.revrobotics.com/java/com/revrobotics/cansparkmax)
* [CANSparkMax Examples Library](https://github.com/REVrobotics/SPARK-MAX-Examples/tree/master/Java)

**Comment by Node-Kid** [comment]
Finished all math that would be useful to robot, might need to add more depending on what we do
